export const blankSchol = {
    ScholarshipName: "",
    OpeningDate:"",
    ExpirationDate: "",
    Amount: 0,
    ApplicationLink: "",
    CitizenshipStatus: [],
    CollegeLevel: "",
    Description: "",
    Ethnicity: [],
    Interests: [],
    maxGPA: 4,
    minGPA: 0,
    Provider: "",
    StateOfResidency: "",
    TypeOfProgram: "",
  }